remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

baseurl: Zandbak
apiname: Meldingen
url: "http://localhost:4000"
nav:
  - title: Item 1
    subnav:
      - title: Subitem 1.1
        path: /path-naar-subitem1.1
  - title: Item 2
    subnav:
      - title: Subitem 2.1
        path: /path-naar-subitem2.1
      - title: Subitem 2.2
        path: /path-naar-subitem2.2
