remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

baseurl: "/"
apiname: "Meldingen"
url: "http://localhost:4000"
nav:
  - title: Item 1
    subnav:
      - title: OAS-spec Meldingen
        path: /oas/meldingen.md
  - title: Item 2
    subnav:
      - title: Subitem 2.1
        path: /path-naar-subitem2.1
      - title: Subitem 2.2
        path: /path-naar-subitem2.2
